class Netflix
{
	static String kannadaMovies[]={"1:kabzaa","2:Shivaji surathkal","3:Kranti","4:Vedha,Kantara","5:777 Charlie","6:Sakath","7:Raghavendra stores","8:Gandhadagudi","9:Gurudev Hoysala","10:Garuda Gamana","11:Avane Srimannarayana","12:love Mocktail","13:Head Bush","14:Totapuri","15:Dilpasand","16:Gaalipata2","17:Roberrt","18:Premam poojyam","19:Kannadiga","20:Love you Rachchu","21:Shiva 143","22:Pogaru","23:Lucky Man","24:By two Love","25:Bhajarangi2","26:Salaga","27:Act 1978"};
	static String teluguMovies[]={"1:Dasara","2:Virupaksha","3:Agent","4:Butta Bomma","5:Ramabanam","6:Veera Simha","7:Ravanasura","8:Custody","9: 18 pages","10:Hit","11:Dhamaka","12:Uravukal","13:Vaathi","14:Ugram","15:Pushpa","16:RRR","17:Karthikeya2","18:Acharya","19:The Warriorr","19:Sita Ramam","20:Bimbisara","21:DJ tillu","22:Virata parvam","23:Ori devuda","24:Godfather","25:Varudu kaavalenu","26:Men too","27:Pelli sandad","28:Vimanam","29:Theghost","30:Liger"};
	static String malayalamMovies[]={"1: 2018","2: Charles enterprises","3: sulaikha manzil","4: Ayalvaashi","5: Romancham","6: Pachuvum" ,"7: Iratta","8: Njaan","9: Janaki jaane","10: Kolla","11: Thrishanku","12: Poovan","13: Ayisha","14: Enthada saji","15: Dear vaappi","16: Pookkaalam","17: Christy"};
	static String hindiMovies[]={"1: Bhediya","2: Vikram Vedha","3: u-turn","4: Bholaa","5: Selfiee","6: Pathaan","7: Kathal","8: Gulmohar","9: Afwaah","10: Bawaal","11: Bloody daddy","12: Tarla","13: Uunchai","14: Drishyam2","15: Cirkus","16: Mumbaikar","17: Darlings","18: Shehzada","19: Sergeant","20: Blind"};
	static String englishMovies[]={"1: Prey","2: The outfit","3: Avatar","4: The whale","5: pearl","6: Black panter","7: Top gun maverick","8: The black phone","9: The menu","10: Aftersun","11: She said","12: Terrifier2","13: True spirit","14: Heart of stone","15: Extraction 2","16: Thirteen lives","17: Love on the rock","18: Wonder women","19: Damsel","20: The monkey King","21: In his shadow","22: Unlock"};
	public static void main(String sanjay[])
	{
		System.out.println("Kannada Movies available in ott platform:");
		System.out.println(kannadaMovies.length);
		System.out.println(kannadaMovies[0]);
		System.out.println(kannadaMovies[1]);
		System.out.println(kannadaMovies[2]);
		System.out.println(kannadaMovies[3]);
		System.out.println(kannadaMovies[4]);
		System.out.println(kannadaMovies[5]);
		System.out.println(kannadaMovies[6]);
		System.out.println(kannadaMovies[7]);
		System.out.println(kannadaMovies[8]);
		System.out.println(kannadaMovies[9]);
		System.out.println(kannadaMovies[10]);
		System.out.println(kannadaMovies[11]);
		System.out.println(kannadaMovies[12]);
		System.out.println(kannadaMovies[13]);
		System.out.println(kannadaMovies[14]);
		System.out.println(kannadaMovies[15]);
		System.out.println(kannadaMovies[16]);
		System.out.println(kannadaMovies[17]);
		System.out.println(kannadaMovies[18]);
		System.out.println(kannadaMovies[19]);
		System.out.println(kannadaMovies[20]);
		System.out.println(kannadaMovies[21]);
		System.out.println(kannadaMovies[22]);
		System.out.println(kannadaMovies[23]);
		System.out.println(kannadaMovies[24]);
		System.out.println(kannadaMovies[25]);
		System.out.println(kannadaMovies[26]);
		System.out.println("--------------------------------------------------------------------");
		System.out.println("Telugu Movies available in ott platform: ");
		System.out.println(teluguMovies[0]);
		System.out.println(teluguMovies[1]);
		System.out.println(teluguMovies[2]);
		System.out.println(teluguMovies[3]);
		System.out.println(teluguMovies[4]);
		System.out.println(teluguMovies[5]);
		System.out.println(teluguMovies[6]);
		System.out.println(teluguMovies[7]);
		System.out.println(teluguMovies[8]);
		System.out.println(teluguMovies[9]);
		System.out.println(teluguMovies[10]);
		System.out.println(teluguMovies[11]);
		System.out.println(teluguMovies[12]);
		System.out.println(teluguMovies[13]);
		System.out.println(teluguMovies[14]);
		System.out.println(teluguMovies[15]);
		System.out.println(teluguMovies[16]);
		System.out.println(teluguMovies[17]);
		System.out.println(teluguMovies[18]);
		System.out.println(teluguMovies[19]);
		System.out.println(teluguMovies[20]);
		System.out.println(teluguMovies[21]);
		System.out.println(teluguMovies[22]);
		System.out.println(teluguMovies[23]);
		System.out.println(teluguMovies[24]);
		System.out.println(teluguMovies[25]);
		System.out.println(teluguMovies[26]);
		System.out.println(teluguMovies[27]);
		System.out.println(teluguMovies[28]);
		System.out.println(teluguMovies[29]);
		System.out.println("-----------------------------------------------------------------");
		System.out.println("Malayalam movies available in ott platform:");
        System.out.println(malayalamMovies[0]);
		System.out.println(malayalamMovies[1]);
		System.out.println(malayalamMovies[2]);
		System.out.println(malayalamMovies[3]);
		System.out.println(malayalamMovies[4]);
		System.out.println(malayalamMovies[5]);
		System.out.println(malayalamMovies[6]);
		System.out.println(malayalamMovies[7]);
		System.out.println(malayalamMovies[8]);
		System.out.println(malayalamMovies[9]);
		System.out.println(malayalamMovies[10]);
		System.out.println(malayalamMovies[11]);
		System.out.println(malayalamMovies[12]);
		System.out.println(malayalamMovies[13]);
		System.out.println(malayalamMovies[14]);
		System.out.println(malayalamMovies[15]);
		System.out.println(malayalamMovies[16]);
		System.out.println("----------------------------------------------------------------");
		System.out.println("Hindi movies available in ott platform:");
		System.out.println(hindiMovies[0]);
		System.out.println(hindiMovies[1]);
		System.out.println(hindiMovies[2]);
		System.out.println(hindiMovies[3]);
		System.out.println(hindiMovies[4]);
		System.out.println(hindiMovies[5]);
		System.out.println(hindiMovies[6]);
		System.out.println(hindiMovies[7]);
		System.out.println(hindiMovies[8]);
		System.out.println(hindiMovies[9]);
		System.out.println(hindiMovies[10]);
		System.out.println(hindiMovies[11]);
		System.out.println(hindiMovies[12]);
		System.out.println(hindiMovies[13]);
		System.out.println(hindiMovies[14]);
		System.out.println(hindiMovies[15]);
		System.out.println(hindiMovies[16]);
		System.out.println(hindiMovies[17]);
		System.out.println(hindiMovies[18]);
		System.out.println(hindiMovies[19]);
		System.out.println("-----------------------------------------------------------------------");
		System.out.println("English movies available in ott platform:");
		System.out.println(englishMovies[0]);
		System.out.println(englishMovies[1]);
		System.out.println(englishMovies[2]);
		System.out.println(englishMovies[3]);
		System.out.println(englishMovies[4]);
		System.out.println(englishMovies[5]);
		System.out.println(englishMovies[6]);
		System.out.println(englishMovies[7]);
		System.out.println(englishMovies[8]);
		System.out.println(englishMovies[9]);
		System.out.println(englishMovies[10]);
		System.out.println(englishMovies[11]);
		System.out.println(englishMovies[12]);
		System.out.println(englishMovies[13]);
		System.out.println(englishMovies[14]);
		System.out.println(englishMovies[15]);
		System.out.println(englishMovies[16]);
		System.out.println(englishMovies[17]);
		System.out.println(englishMovies[18]);
		System.out.println(englishMovies[19]);
		System.out.println(englishMovies[20]);
		System.out.println(englishMovies[21]);
		
	}
}	

 